---
title: "STUDIO"
author: "Damiano Fumagalli"
date: "`r Sys.Date()`"
output: html_document
---
# ESERCIZI CON DATABASE WHO

```{r}
library(readr)
library(tidyr)
library(dplyr)
library(lubridate)
library(stringr)
```

> FILTRARE LE COLONNE CHE INIZIANO PER new_sp_ E PRELEVARE SOLO I VALORI VALIDI

```{r}
selection = who %>% select(starts_with("new_sp_"))
colnames(selection)
oggDaFiltrare = who %>% select(starts_with("new_sp_")) 

# LISTA VUOTA 
nuovo = vector("list", length = ncol(oggDaFiltrare))
for (i in 1:ncol(oggDaFiltrare)){
  # RIMUOVE I DATI NON VALIDI DALLA COLONNA i-esima
  nuovo[i] = oggDaFiltrare[i] %>% filter(!is.na(oggDaFiltrare[i]))
}  
# RIMOZIONE PARTE INUTILE DEL NOME
colnames(oggDaFiltrare) = str_replace(colnames(oggDaFiltrare),"new_sp_","")

nuovo2 = vector("list", length = ncol(oggDaFiltrare))
# IL NOME DELLA VARIABILE ORA CONTIENE 2 INFORMAZIONI, SESSO E ETÀ
oggDaFiltrare %>% pivot_longer(new_sp_m014:newrel_f65, names_to = "key",values_to = "cases", values_drop_na = TRUE )



nuovo2

```

