TITLE Equazione
;risoluzione di un'equazione di secondo grado
.MODEL SMALL
.STACK
.DATA
X DB 00H
B DB 00H
A DB 00H
DUE DB 02H
.CODE
.STARTUP
MOV DX, 0004H		;DL=4
MOV AH, 01H
INT 21H			;INPUT DA TASTIERA
SUB AL, 30H		;AL IN NUMERO
MOV CL, AL		;TERMINE NOTO CL
INT 21H			;INPUT DA TASTIERA
SUB AL, 30H		;AL IN NUMERO
MOV B, AL		;COEFF X
MOV BL, AL
INT 21H			;INPUT DA TASTIERA COEFF X^2
SUB AL, 30H		;AL IN NUMERO
MOV A, AL		;A=AL

;CALCOLO DEL DISCRIMINANTE
;B^2-4*A*C
PUSH AX			;SALVATAGGIO AL NELLO STACK
MOV AL, BL		;AL=BL
MUL BL			;AX=AL*BL=BL^2=B^2
MOV BX, AX		;BX=B^2
POP AX			;SALVATAGGIO DEL VALORE NELLO STACK IN AL
MOV AH, 00H		;AZZERAMENTO AH
MUL CL			;AX=AL*CL
MUL DL			;AX=AL*4	4*A*C

SUB BX, AX		;BX=BX-AX=B^2-4*A*C		DISCRIMINANTE
CMP BX, 00H
JE UGUALE		;SE UGUALE SALTA A UGUALE
JB FINE		;SE MINORE SALTA A MINORE


UGUALE: MOV DH, 00H
		MOV DL, B		;DL=B
		MOV AL, A		;AL=A
		MUL DUE			;AX=AL*2
		XCHG DX, AX		;SCAMBIO DI DX E AX
		DIV DL			;AL=AX/DL=B/2A
		MOV X, AL		;X=AL
		MOV DL, X		;DL=X
		ADD DL, 30H		;DL IN CARATTERE
		MOV AH, 02H
		INT 21H			;OUTPUT DA DL
		JMP FINE
		



FINE: MOV AH, 4CH
		INT 21H			;SERVIZIO DOS DI CHIUSURA
END