TITLE CALC
;CALCOLATRICE
.MODEL SMALL
.DATA

.STACK
.CODE
.STARTUP
MOV AX, 00H
MOV BX, 00H
MOV CX, 00H
MOV DX, 00H


MOV AH, 01H
INT 21H			;INPUT DA TASTIERA IN AL DEL PRIMO OPERANDO
MOV BL, AL		;BL=AL		1 OPERANDO
SUB BL, 30H		;BL IN NUMERO


INT 21H			;INPUT IN AL DELL'OPERATORE
MOV CL, AL		;CL=AL
CMP CL, '+'
JE SOMMA
CMP CL, '-'
JE SOTTRAZIONE
CMP CL, '*'
JE PRODOTTO
CMP CL, '/'
JE DIVISIONE
JMP FINE


SOMMA:	MOV AH, 01H
		INT 21H			;INPUT IN AL DEL SECONDO OPERANDO
		SUB AL, 30H		;AL IN NUMERO
		PUSH AX			;METTE AX NELLO STACK
		
		MOV DL, 3DH		;COD ASCII DELL'=
		MOV AH, 02H
		INT 21H			;OUTPUT DA DL
		
		POP AX			;METTE IL CONTENUTO DELLO STACK NEL REGISTRO AX
		ADD BL, AL		;BL=BL+AL
		ADD BL, 30H		;IL NUMERO DEVE ESSERE TRASFORMATO IN CARATTERE SOMMANDO IL COD ASCII DELLO 0 (30H)
		MOV DL, BL		;DL=BL
		MOV AH, 02H
		INT 21H			;OUTPUT DA DL DEL RISULTATO DELL'OPERAZIONE
		JMP FINE		

SOTTRAZIONE:	MOV AH, 01H
				INT 21H			;INPUT IN AL DEL SECONDO OPERANDO
				SUB AL, 30H		;AL IN NUMERO
				PUSH AX			;METTE AX NELLO STACK
				
				MOV DL, 3DH		;COD ASCII DELL'=
				MOV AH, 02H
				INT 21H			;OUTPUT DA DL
				
				POP AX			;PRELEVA IL CONTENUTO DELLO STACK E LO METTE NEL REGISTRO AX
				SUB BL, AL		;BL=BL-AL
				
				ADD BL, 30H		;BL IN CARATTERE
				MOV DL, BL		;DL=BL
				MOV AH, 02H
				INT 21H			;OUTPUT DA DL DEL RISULTATO DELL'OPERAZIONE
				JMP FINE


PRODOTTO:		MOV AH, 01H
				INT 21H			;INPUT IN AL DEL SECONDO OPERANDO
				PUSH AX			;METTE AL NELLO STACK PER SALVARE IL DATO
				
				MOV DL, 3DH		;COD ASCII DELL'=
				MOV AH, 02H
				INT 21H			;OUTPUT DA DL
				
				POP AX
				SUB AL, 30H		;AL IN NUMERO
				MUL BL			;AX=AL*BL
				ADD AL, 30H		;AX IN CARATTERE
				MOV DL, AL		;DL=AX
				MOV AH, 02H
				INT 21H			;OUTPUT DI AX
				JMP FINE


DIVISIONE:		MOV AH, 01H
				INT 21H			;INPUT IN AL DEL SECONDO OPERANDO
				PUSH AX			
				
				MOV DL, 3DH		;COD ASCII DELL'=
				MOV AH, 02H
				INT 21H			;OUTPUT DA DL
				
				POP AX
				SUB AL, 30H		;AL IN NUMERO
				XCHG AX, BX		;SCAMBIA I DUE NUMERI (1OP DA BL A AL) E VICEVERSA
				DIV BL			;AX/BL		RISULTATO IN AL   RESTO IN AH
				ADD AL, 30H
				MOV DL, AL		;DL = AL
				MOV AH, 02H
				INT 21H			;OUTPUT DA DL
				JMP FINE
				


FINE:	MOV AH, 4CH
		INT 21H

END
