TITLE CONVERSIONE
;CONVERSIONE IN BINARIO DEL COD ASCII DI UN CARATTERE IN INPUT DA TASTIERA 8 BIT
.MODEL SMALL
.STACK
.DATA
.CODE
MOV CL, 00H			;INIZIALIZZAZIONE CONTATORE CL A 0
MOV DL, 02H
MOV AH, 01H
INT 21H				;INPUT IN AL

MOV AH, 00H			;AZZERAMENTO AH
CICLO:	DIV DL		;AX/DUE		AH=RESTO  AL=QUOZIENTE
		PUSH AX		;SALVATAGGIO DI AH NELLO STACK
		MOV AH, 00H	;AZZERAMENTO DEL RESTO
		INC CX		;INCREMENTO DEL CONTATORE
		CMP CX, 08H	
		JB CICLO	;SE CX<8 SALTA A CICLO

MOV CX, 00H			;AZZERAMENTO DEL CONTATORE
MOV DL, 20H			;COD ASCII DELLO SPAZIO
MOV AH, 02H
INT 21H				;STAMPA DA DL		
STAMPA: POP DX		;DL=STACK
		XCHG DH, DL
		ADD DL, 30H			;DL IN CARATTERE
		MOV AH, 02H
		INT 21H		;STAMPA DA DL
		INC CL		;INCREMENTO DEL CONTATORE CX
		CMP CL, 08H	
		JB STAMPA	;SE CX<8 SALTA A STAMPA
		
MOV AH, 4CH
INT 21H				;SERVIZIO DOS DI CHIUSURA



END