TITLE MEDIA
.MODEL SMALL
.STACK
.DATA
N DB ?
I DB 00H
.CODE
MOV CX, 0000H	;CX=SOMMA
MOV BX, 000H	;BX=MEDIA
.STARTUP
MOV AH, 01H
INT 21H			;INPUT DA TASTIERA DI N	IN AL	N=QUANTI NUMERI INSERIRE
SUB AL, 30H		;AL IN NUMERO
MOV N, AL		;N=AL
MOV DL, N 	;DL=N
MOV BL, I	;BL=I
CICLO:	MOV AH, 01H
		INT 21H		;INPUT IN AL 
		SUB AL, 30H	;AL IN NUMERO
		ADD CL, AL	;CL=CL+AL
		ADD BL, 01H		;I++
		CMP BL, DL
		JB CICLO	;SALTA A CICLO SE I<N
		JMP FINE

FINE: MOV AH, 00H			;AZZERAMENTO DI AH
MOV AL, CL			;AL=CL
DIV N 				;AL=AX/N  =	SOMMA/N  = 	MEDIA
PUSH AX				;SALVATAGGIO DI AL NELLO STACK
MOV DL, 20h			;CODICE ASCII DELLO SPAZIO
MOV AH, 02H
INT 21H				;OUTPUT DA DL DELLO SPAZIO
POP DX				;DL=STACK
ADD DX, 30H			;DX IN CARATTERE
MOV AH, 02H
INT 21H				;OUTPUT DA DL DELLA MEDIA
		

END